basePath: /
definitions:
  handler.HealthResponse:
    properties:
      status:
        example: UP
        type: string
      timestamp:
        example: "2026-07-04T01:07:40+05:30"
        type: string
    type: object
host: localhost:1700
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a production-ready boilerplate Go microservice API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Microservice Boilerplate API
  version: "1.0"
paths:
  /health:
    get:
      description: Get the health status of the microservice
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthResponse'
      summary: Health Check
      tags:
      - System
swagger: "2.0"
